package com.bellogate.weatherapplication.ui.util

enum class UIState {

    SEARCHING_FOR_CURRENT_WEATHER_REPORT,
    FOUND_CURRENT_WEATHER_REPORT,
    FAILED_TO_FIND_CURRENT_WEATHER_REPORT,
    SEARCHING_FOR_CUSTOM_WEATHER_REPORT,
    FOUND_CUSTOM_WEATHER_REPORT,
    FAILED_TO_FIND_CUSTOM_WEATHER_REPORT,
    PERMISSION_NOT_GRANTED
}